-- CreateTable
CREATE TABLE "User" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "points" INTEGER NOT NULL,
    "avatar" TEXT NOT NULL DEFAULT ''
);

-- CreateTable
CREATE TABLE "Date" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "game" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "_DateToUser" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,
    CONSTRAINT "_DateToUser_A_fkey" FOREIGN KEY ("A") REFERENCES "Date" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_DateToUser_B_fkey" FOREIGN KEY ("B") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "_DateToUser_AB_unique" ON "_DateToUser"("A", "B");

-- CreateIndex
CREATE INDEX "_DateToUser_B_index" ON "_DateToUser"("B");
